# STRINGD ARE IMMUTABLE

a = "Dhruv  !!!!!! "
#SUPPOSE WE WANT TO CALCULATE THE LENGTH OF A STRING THEN WE USE "LEN" TO CALCULATE THE LENGTH OF STRING----
print(len(a))
# ----BY WRITING "UPPER" ALL THE LETTERS IN A WILL BE CONVERTED IN UPPERCAE LETTERS----
print(a.upper())
# ----BY WRITING "LOWER" ALL THE LETTERS ARE CONERTED INTO LOWER CARS CASWS
print(a.lower())
#----SUPPOSE WE HAVE TO REMOVE "!" EXCLAMATORY SIGN FROM DHRUV THEN WE USE RSTRIP TO REMOVE THAT SIGN----
print(a.rstrip("!"))
#---- SUPPOSE WE WANT TO CHANGE THE NAME DHRUV TO JOHN ... FOR THAT WE USE "REPLCE" TO REPLCE ANY FROM THE STRING----
print(a.replace("Dhruv" , "John"))
#----SUPPOSE WE WANT TO MAKE A LIST FOR A STRING THAN WE USE "SPLIT"---
print(a.split(" "))
#----SUPPOSE WE FORGET TO TYPE THE FIRST LETTER OF HEADING AS UPPERCASE SO BY WRITING "CAPITALIZE" WE CAN CHANGE THE FIRST LETTER OF OUR ALSO IT WILL CONVERT ALL REMAINING INTO LOWERCASE----
heading = "introduction to java!!!!"
print(heading.capitalize())
print(len(heading.center(50)))
